name: nicolasdussart
favicon: null
layout_spectrum: 0.5728923955466598
typography_spectrum: 0.6853091844823211
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6965998136438429
  lightness: 0.057590165408328176
  saturation: 0.4754497075919062
  rhythmicContrast: 0.8884774106554687
purpose: []
